quotes/quoteapp/urls.py
from django.urls import path, re_path
from . import views

app_name = 'quoteapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('tag/', views.tag, name='tag'),
    path('author/', views.author, name='author'),
    path('quote/', views.quote, name='quote'),
    path('detail/<int:quote_id>', views.detail, name='detail'),
    path('author_detail/<int:author_id>', views.author_detail, name='author_detail'),
    path('delete/<int:quote_id>', views.delete_quote, name='delete'),
    #path('', views.main, name='main'),
    #re_path('', views.main, name='main'),
]

quotes/quotes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quoteapp.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html',
                                          success_url='/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes/quoteapp/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=100, null=False, unique=True)
    born_date = models.CharField(max_length=30, null=False)
    born_location = models.CharField(max_length=255, null=False)
    description = models.TextField(null=False)    

    def __str__(self):
        return f"{self.fullname}"


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self):
        return f"{self.name}"


class Quote(models.Model):
    quote = models.CharField(max_length=1100, null=False)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)   
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return f"{self.quote}"

quotes/quoteapp/forms.py
from django.forms import ModelForm, CharField, TextInput, Textarea
from .models import Tag, Author, Quote


class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    
    class Meta:
        model = Tag
        fields = ['name']


class AuthorForm(ModelForm):

    fullname = CharField(min_length=3, max_length=50, required=True, widget=TextInput())
    born_date = CharField(min_length=3, max_length=30, required=True, widget=TextInput())
    born_location = CharField(min_length=3, max_length=50, required=True, widget=TextInput())
    description = CharField(min_length=3, required=True, widget=Textarea)   

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class QuoteForm(ModelForm):

    quote = CharField(min_length=10, max_length=255, required=True, widget=Textarea)  

    class Meta:
        model = Quote
        fields = ['quote']
        exclude = ['author', 'tags']

quotes/quoteapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import TagForm, AuthorForm, QuoteForm
from .models import Tag, Author, Quote
from django.db.models import Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def main(request, tag_id=None):
    if request.GET.get('tag_id') != None:
        tag = Tag.objects.get(id=request.GET.get('tag_id'))
        quotes = Quote.objects.filter(tags=tag)
    else:
        quotes = Quote.objects.all()

    tag_size_block = list(range(28, 8, -2))
    most_used_tags = get_most_used_tags()
    paginator = Paginator(quotes, 10)
    page_number = request.GET.get('page')
    try:
        quotes = paginator.page(page_number)
    except PageNotAnInteger:
        quotes = paginator.page(1)
    except EmptyPage:
        quotes = paginator.page(paginator.num_pages)

    return render(request, 'index.html', {"quotes": quotes, "tag_size_block": tag_size_block, "most_used_tags": most_used_tags})


@login_required
def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'tag.html', {'form': form})

    return render(request, 'tag.html', {'form': TagForm()})


@login_required
def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'author.html', {'form': form})

    return render(request, 'author.html', {'form': AuthorForm()})


@login_required
def quote(request):
    tags = Tag.objects.all()
    authors = Author.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save(commit=False)
            new_quote.author_id = request.POST['author']  
            new_quote.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)     

            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quote.html', {"authors": authors, "tags": tags, 'form': form})

    return render(request, 'quote.html', {"authors": authors, "tags": tags, 'form': QuoteForm()})


def detail(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id)
    author = get_object_or_404(Author, pk=quote.author_id)
    return render(request, 'detail.html', {"quote": quote, "author": author})


def author_detail(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'author_detail.html', {"author": author})


def delete_quote(request, quote_id):
    Quote.objects.get(pk=quote_id).delete()
    return redirect(to='quoteapp:main')


def get_most_used_tags():
    most_used_tags = Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:10]
    return most_used_tags

quotes/quoteapp/templates/author.html
{% extends "base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the author fullname:
            {{form.fullname}}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label>Enter the author's born date:
            {{form.born_date}}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>    
    <div style="padding: 10px">
        <label>Enter the author's born location:
            {{form.born_location}}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>        
    <div style="padding: 10px">
        <label>Enter description about author:
            {{form.description}}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>            
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/quoteapp/templates/author_detail.html
{% extends "base.html" %} {% block content %}

<h2>{{author.fullname}}</h2>
<p>Born date: <small>{{author.born_date}}</small></p>
<p>Born location: <strong>{{author.born_location}}</strong></p>
<p><strong>Description:</strong></p><div>{{author.description}}</div>

{% endblock %}

quotes/quoteapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Quotes</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="/" role="button"> Go back to the main page </a></li>
        </ul>
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

quotes/quoteapp/templates/detail.html
{% extends "base.html" %} {% load extract_tags %} {% block content %}

<p>Quote: <b>{{quote.quote}}</b></p>
<p>Author: <a href="{% url 'quoteapp:author_detail' author.id %}" role="button" class="outline">{{quote.author}}</a></p>
<p>Tags: <small> {{ quote.tags|tags }} </small></p>

{% endblock %}

quotes/quoteapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Quotes</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>

    <div class="container">
        <div class="row header-box">
            <div class="col-md-3">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes</a>
                </h1>
            </div>
            <div class="col-md-9">
                <div class="quote-menu-container">
                    {% if user.is_authenticated %}
                    <div class="quote-menu">
                        <div class="user-menu">
                            <ul>
                                <li><a href="{% url 'quoteapp:quote' %}" role="button">Add quote</a></li>
                                <li><a href="{% url 'quoteapp:author' %}" role="button">Add Author</a></li>
                                <li><a href="{% url 'quoteapp:tag' %}" role="button">Add Tag</a></li>
                            </ul>
                        </div>
                        <div class="user-login-menu">
                            <ul>
                                <li>Welcome <b>{{ user.username }}!</b></li>
                                <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
                            </ul>
                        </div>
                    </div>
                    {% else %}
                    <div class="quote-menu">
                        <ul>
                            <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
                            <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
                        </ul>
                    </div>
                    {% endif %}  
                </div>               
            </div>
        </div>          

        <div class="row">
            <div class="col-md-8">
                {% if rquotes %}
                    <div class="received_quotes">{{rquotes}}</div>
                {% endif %} 

                {% for quote in quotes %}
                <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                    <span class="text" itemprop="text">“{{ quote.quote }}”</span>
                    <span>by <small class="author" itemprop="author">{{quote.author}}</small>
                    <a href="{% url 'quoteapp:author_detail' quote.author_id %}">(about)</a>
                    </span>
                    <div class="tags">
                        <meta class="keywords" itemprop="keywords" content="simplicity,understand"> 
                        Tags: 
                        {% load extract_tags %}
                        {% for tag in quote.tags|tags %}
                            <a class="tag" href="{% url 'quoteapp:main' %}?tag_id={{tag.id}}">{{tag.name}}</a>
                        {% endfor %}
                        {% if user.is_authenticated and user.is_superuser %}
                        <a href="{% url 'quoteapp:delete' quote.id %}" role="button" style="color:rgb(255, 0, 0)"> X </a>
                        {% endif %} 
                    </div>
                </div>
                {% endfor %}       

                <nav>
                    <ul class="pager">
                        
                        <li class="previous">
                            {% if quotes.has_previous %}
                            <a href="?page=1"><span aria-hidden="true">←←</span> First</a>
                            <a href="?page={{ quotes.previous_page_number }}"><span aria-hidden="true">←</span> Previous</a>
                            {% endif %}                        
                        </li>
                        
                        <span class="current">
                            Page {{ quotes.number }} of {{ quotes.paginator.num_pages }}.
                        </span>

                        <li class="next">
                            {% if quotes.has_next %}
                            <a href="?page={{ quotes.paginator.num_pages }}">Last <span aria-hidden="true">→→</span></a>
                            <a href="?page={{ quotes.next_page_number }}">Next <span aria-hidden="true">→</span></a>
                            {% endif %}
                        </li>
                    </ul>
                </nav>
            </div>

        
            <div class="col-md-4 tags-box">
                <div class="top_ten_tags">
                    <h2>Top Ten tags</h2>
                    {% for tag in most_used_tags %}
                        <span class="tag-item">
                            <a class="tag" style="font-size: 30px" href="{% url 'quoteapp:main' %}?tag_id={{tag.id}}">{{ tag.name }}</a> ({{ tag.num_quotes }} quotes)
                        </span>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
            <p class="text-muted">
                Quotes by: <a href="https://www.goodreads.com/quotes">GoodReads.com</a>
            </p>
            <p class="copyright">
                Made by <span class="zyte">Alex_Tsyb</span>
            </p>
        </div>
    </footer>

    <div id="gadsf21g"></div><div at-magnifier-wrapper=""><div class="at-theme-light"><div class="at-base notranslate" translate="no"><div class="EuwGd" style="top: 0px; left: 0px;"></div></div></div></div>

</body>
</html>

quotes/quoteapp/templates/quote.html
{% extends "base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Select Author:
            <select name="author" required>
                {% for author in authors %}
                <option value="{{author.id}}">{{author.fullname}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div style="padding: 10px">
        <label> Quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

quotes/quoteapp/templates/tag.html
{% extends "base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}